source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NHSearchViewController_Example', :exclusive => true do
  pod "NHSearchController", :path => "../"
end

target 'NHSearchViewController_Tests', :exclusive => true do
  pod "NHSearchController", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
